package utils;

public enum ErrorType {
    FILE_ACCESS_DENIED,
    EXPECTED_FOLDER,
    BAD_PARAMETER_FILE,
    COLUMN_MISSING,
    INVALID_LINKAGE_TYPE,
    INVALID_VALUE_MEMBER,
    INVALID_MODE,
    UNEXPECTED_EMPTY_CELL,
    EVALUATION_MODE_STATE_ERROR,
    EVALUATION_ALL_NULL_ERROR,
    INVALID_GUARD,
    INVALID_EFFECT,
}
